---

- name: Admin users
  user:
    name: "{{ item }}"
    state: present
    groups: sudo
  loop: "{{ admin_users }}"

- name: Admin users .ssh directories
  file:
    path: /home/{{ item }}/.ssh
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "u=rwx,go="
  loop: "{{ admin_users }}"

- name: Find admin user 'mortal' authorized keys to copy
  stat:
    path: "{{ role_path }}/files/{{ item }}_mortal.keys"
  loop: "{{ admin_users }}"
  delegate_to: localhost
  register: st

- name: Install admin user 'mortal' authorized keys
  copy:
    src: "{{ item.stat.path }}"
    dest: ~{{ item.item }}/.ssh/authorized_keys
    owner: "{{ item.item }}"
    group: "{{ item.item }}"
    mode: "u=rw,go="
  loop: "{{ st.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.stat.exists

- name: root's .ssh directory
  file:
    path: ~root/.ssh
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go="

- name: Install admin user 'priv' keys into root authorized_keys
  assemble:
    remote_src: false
    src: "{{ role_path }}/files/"
    dest: ~root/.ssh/authorized_keys
    regexp: "[a-z0-9_]+_priv.keys"
    owner: root
    group: root
    mode: "u=rw,go="
