---

- name: Install default packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - openssh-server
      - emacs
      - git
      - unzip
      - ssmtp
    state: present

- name: System-wide ssh known_hosts file
  copy:
    src: ssh_known_hosts
    dest: /etc/ssh

- name: Configure ssmtp
  copy:
    src: "{{ item }}"
    dest: /etc/ssmtp
    owner: root
    group: root
    mode: "u=rw,go=r"
  loop:
    - ssmtp.conf
    - revaliases
