---

- name: Install default packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - openssh-server
      - emacs
      - git
      - openjdk-8-jdk
      - ssmtp
      - python3
      - python3-pip
      - python3-venv
      - postgresql
      - postgresql-contrib
      - postgis
      - python3-psycopg2
      - python-psycopg2     # For Ansible!
    state: present

- name: Upgrade pip3
  command: python3 -m pip --version
  changed_when: false

- name: System-wide ssh known_hosts file
  copy:
    src: ssh_known_hosts
    dest: /etc/ssh

- name: update_known_hosts.sh
  copy:
    src: update_known_hosts.sh
    dest: /usr/local/bin
    mode: "+x"

- name: Configure ssmtp
  copy:
    src: "{{ item }}"
    dest: /etc/ssmtp
    owner: root
    group: root
    mode: "u=rw,go=r"
  loop:
    - ssmtp.conf
    - revaliases
