---

- name: reload systemd
  systemd:
    daemon_reload: yes
  listen: "reload systemd"

- name: restart prometheus
  service:
    name: prometheus
    state: restarted
  listen: "restart prometheus"

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
  listen: "restart node_exporter"

- name: restart statsd_exporter
  service:
    name: statsd_exporter
    state: restarted
  listen: "restart statsd_exporter"

- name: restart grafana-server
  service:
    name: grafana-server
    state: restarted
  listen: "restart grafana-server"
