global:
  scrape_interval: 15s

scrape_configs:

  # Built-in prometheus metrics 
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/system/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

  # Server metrics via node_exporter
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  # Gunicorn metrics via statsd_exporter
  - job_name: 'statsd_exporter'
    static_configs:
      - targets: ['localhost:9102']

  # Nginx metrics via Prometheus Lua metric library 
  - job_name: 'nginx'
    scrape_interval: 5s
    metrics_path: '/system/nginx/metrics'
    static_configs:
      - targets: ['localhost']
