---

- hosts: tfc_servers
  roles:
    - { role: common,        tags: ["common"] }
    - { role: users,         tags: ["users"] }
    - { role: file_systems,  tags: ["file_systems"] }
    - { role: tfc_webserver, tags: ["tfc_webservers"] }
    - { role: tfc_prod,      tags: ["tfc_prod"] }
    - { role: monit,         tags: ["monit"] }
