---

- hosts: tfc_servers
  roles:
    - { role: common,        tags: ["common"] }
    - { role: users,         tags: ["users"] }
    - { role: file_systems,  tags: ["file_systems"] }
    - { role: tfc_webserver, tags: ["tfc_webservers"] }
    - { role: tfc_prod,      tags: ["tfc_prod"] }
    - { role: monit,         tags: ["monit"] }
    - { role: system_metrics, tags: ["system_metrics"] }

- hosts: tfc_servers
  become: true
  become_user: postgres
  roles:
    - { role: tfc_web_postgres, tags: ["tfc_web_postgres"] }

- hosts: tfc_servers
  become: true
  become_user: tfc_prod
  roles:
    - { role: tfc_web,        tags: ["tfc_web"] }